version: '3.8'

services:
  front-mycontacts:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=3000
    command: ['yarn', 'start']
